r"""Inline the section files into a single total_main.tex (2026-09-24).

main.tex \input{}s eight section files.  This writes one self-contained document with those bodies
substituted in place, for sending the manuscript as a single file or for tools that want one input.
Everything else the build needs is unchanged: main.tex's preamble travels with it, and style/, the .bib
files and figure/ are still required.

The generated file is an output, not a source.  Edit the section files and regenerate; edits made to
total_main.tex are discarded by the next run, which is why the file says so at its top.

    python scripts/flatten_paper.py                 # writes writting_docs/paper/total_main.tex
    python scripts/flatten_paper.py --check         # verify it matches the section files, write nothing
"""
import argparse, os, sys

ORDER = ['0_Abstract', '1_Intro', '6_Related', '2_Analysis', '3_Method', '4_Experiments',
         '7_Conclusion', '5_Appendix']
HEAD = """% total_main.tex -- the eight section files inlined into one document, generated by
% scripts/flatten_paper.py.  Everything else (main.tex's preamble, style/, the .bib files, figure/) is
% unchanged and still required to build.  Edit the section files, not this one: regenerate it instead,
% or the next regeneration silently discards the edits.
%
"""


def flatten(d):
    out = open(os.path.join(d, 'main.tex')).read()
    for name in ORDER:
        body = open(os.path.join(d, name + '.tex')).read().rstrip('\n')
        rule = '%% ' + '=' * 76
        banner = '%s\n%%%% %s.tex\n%s' % (rule, name, rule)
        pat = '\\input{%s}' % name
        if out.count(pat) != 1:
            raise SystemExit('main.tex has %d occurrences of %s' % (out.count(pat), pat))
        out = out.replace(pat, banner + '\n' + body + '\n')
    return HEAD + out


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--dir', default=os.path.join(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))), 'writting_docs', 'paper'))
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    text = flatten(a.dir)
    path = os.path.join(a.dir, 'total_main.tex')
    if a.check:
        cur = open(path).read() if os.path.exists(path) else None
        if cur != text:
            print('total_main.tex is out of date; rerun without --check')
            sys.exit(1)
        print('total_main.tex matches the section files')
    else:
        open(path, 'w').write(text)
        print('wrote %s (%d lines)' % (path, text.count('\n') + 1))
